version: '3.7'
services:
  flask-app:
    image: flask-app
    build: ./flask-app
    depends_on:
      - mysql
  mysql:
    image: flask-db
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=flask-db
  nginx:
    image: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - flask-app  
